name: 🐞 Bug Report
description: Report an issue or unexpected behavior
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Before You Begin
      description: |
        Please complete the following before submitting a bug report:
      options:
        - label: I am using the latest available version of Weblo.
          required: true
        - label: I have searched for existing issues related to this bug.
          required: true
          
  - type: input
    id: device_info
    attributes:
      label: Device Info
      placeholder: e.g. Samsung Galaxy A52, Android 13
    validations:
      required: true


  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: |
        Clearly describe the issue. What’s going wrong?
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Screenshots
      placeholder: |
        If applicable, attach screenshots
    validations:
      required: false
